# Ansible playbook to create the pulp service containers image
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yaml
  tasks:
    - name: "Generate Containerfile from template"
      template:
        src: ../molecule/scenario_resources/Dockerfile.j2
        dest: "Containerfile_{{ item.name }}"
      with_items: "{{ molecule_images }}"

    # yamllint disable-file
    - name: "Build molecule image"
      command: "buildah bud -f Containerfile_{{ item.name }} -t molecule_{{ item.name }}:latest ."
      with_items: "{{ molecule_images }}"

    - name: "Push molecule image"
      podman_image:
        name: "molecule_{{ item.name }}"
        push: yes
        username: fao89
        password: "{{ lookup('env','DOCKER_BOT_PASSWORD') }}"
        push_args:
          dest: "docker.io/pulp"
      with_items: "{{ molecule_images }}"
