---
- name: Restart pulpcore-api.service
  systemd:
    name: pulpcore-api.service
    enabled: true
    state: restarted
    daemon_reload: true
  become: true

# Workaround https://github.com/ansible/ansible/issues/34505
# by not using include_tasks
- name: Restart all Pulp services
  include: handlers/restart_all_pulp.yml
  static: no

- name: Collect static content
  command: '{{ pulp_install_dir }}/bin/django-admin collectstatic --noinput --link'
  register: staticresult
  changed_when: "staticresult.stdout is not search('\n0 static files')"
  become: true
  become_user: '{{ pulp_user }}'
  notify: Restart pulpcore-api.service
  environment:
    PULP_SETTINGS: "{{ pulp_settings_file }}"
    PULP_STATIC_ROOT: "{{ pulp_webserver_static_dir }}"
