---

pulp_cache_dir: '/var/lib/pulp/tmp'
pulp_config_dir: '/etc/pulp'
# This var intentionally not advertised to users, because there is no
# foreseeable need for them to change the filename, only pulp_config_dir.
pulp_settings_file: '{{ pulp_config_dir }}/settings.py'
pulp_default_admin_password: ''
# Users should not set this variable, instead using `pulp_settings.databases`
pulp_settings_db_defaults:
  databases:
    default:
      HOST: localhost
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: pulp
      USER: pulp
      PASSWORD: pulp
pulp_install_dir: '/usr/local/lib/pulp'
pulp_install_plugins: {}
pulp_install_api_service: true
# Deprecated unused. Variables for dependency upgrades are TBD
pulp_upgrade: false
#  Intentionally not advertised to users. They should not set this unless
#  they are confident that this version of pulp_installer is compatible with
#  pulp_version.
#  Ignored if pulp_source_dir is set
pulp_version: "3.2.1"
pulp_user: pulp
pulp_user_id:
pulp_group: pulp
pulp_group_id:
pulp_user_home: '/var/lib/pulp'
pulp_static_url: 'assets'
pulp_webserver_static_dir: "{{ pulp_user_home | regex_replace('\\/$', '') }}/{{ pulp_static_url | regex_replace('^\\/|\\/$', '') }}/"
pulp_pip_editable: yes
pulp_use_system_wide_pkgs: false
pulp_api_bind: '127.0.0.1:24817'
prereq_pip_packages: []
pulp_rhel_codeready_repo:
  - codeready-builder-for-rhel-8-x86_64-rpms
  - rhui-codeready-builder-for-rhel-8-rhui-rpms
rhel7_optional_repo:
  - rhui-rhel-7-server-rhui-optional-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-workstation-optional-rpms
epel_release_packages:
  - epel-release
  - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
