---
- block:
    - name: Install PostgreSQL10 Repository
      yum_repository:
        name: postgres
        description: Postgres YUM repo
        baseurl: "https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-{{ ansible_facts.architecture }}"
        gpgkey: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-10
      when:
        - ansible_facts.distribution == 'CentOS'
        - ansible_facts.distribution_major_version|int == 7

    - name: Install and configure PostgreSQL
      include_role:
        name: geerlingguy.postgresql

    - name: Create pg_config symbolic link
      file:
        src: "{{ postgresql_bin_path }}/pg_config"
        dest: "/usr/bin/pg_config"
        state: link
      check_mode: false
      when:
        - ansible_facts.distribution == 'CentOS'
        - ansible_facts.distribution_major_version|int == 7
  become: yes
