---
- name: include_tasks to build Galaxy WebUI if galaxy-ng is among the plugins
  include_tasks:
    file: galaxy_ui.yml
    apply:
      become: true
  when: pulp_install_plugins_normalized['galaxy-ng'] is defined

- import_tasks: install_basic_packages.yml
  become: true

- name: "Add {{ pulp_user }} to systemd-journal group"
  user:
    name: "{{ pulp_user }}"
    groups: systemd-journal
    append: yes
  become: true

- import_tasks: install_podman.yml
  become: true

- import_tasks: install_docs_requirements.yml
  become: true
  become_user: '{{ pulp_user }}'

- import_tasks: bashrc.yml
  become: true
  become_user: "{{ developer_user }}"

- import_tasks: config_files.yml
  become: true
  become_user: "{{ developer_user }}"

- name: Set the message of the day
  copy:
    src: motd
    dest: /etc/motd
    mode: '0644'
  become: true
...
