---
- block:

    - name: Install firewalld
      package:
        name: firewalld
        state: present

    - name: Start and enable firewalld
      systemd:
        name: firewalld
        state: started
        enabled: true

    - name: Accept connections on port 80
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Accept connections on port 443
      ansible.posix.firewalld:
        service: https
        permanent: true
        immediate: true
        state: enabled
      when: not pulp_webserver_disable_https | bool

  become: true
