---
# installation of nginx on ubuntu doesn't do this automatically
- name: Create nginx user
  user:
    name: nginx
    system: true
  when: ansible_distribution == 'Ubuntu'
  become: yes

- block:

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Install Nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx
        - Starting the health check

    - name: Find pulp obsolete symlinks
      find:
        paths: /etc/nginx/conf.d
        file_type: link
        patterns: "pulp*"
      register: old_pulp_symlinks
      tags: cleanup

    - name: Remove pulp obsolete symlinks
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_pulp_symlinks.files }}"
      tags: cleanup

    - name: Create directory for Pulp Nginx snippets
      file:
        path: "/etc/nginx/pulp/"
        state: directory

    # FIXME: The ansible output here over the results is very ugly.
    # It may be a lot cleaner if we were to use the command module,
    # above and/or create a temporary data structure.
    - name: Symlink nginx snippets
      file:
        src: "{{ item.stdout_lines | last }}"
        # Note: item.item is pulp_install_plugins_normalized
        dest: "/etc/nginx/pulp/{{ item.item.key | regex_replace('-', '_') }}.conf"
        state: link
      loop: '{{ snippets.results }}'
      when: item.rc == 0
      notify:
        - reload nginx
        - Starting the health check

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: true
        daemon_reload: true

  become: true
