---
# tasks file for pulp_api
- block:

    - name: Install pulpcore-api service files
      template:
        src: pulpcore-api.service.j2
        dest: /lib/systemd/system/pulpcore-api.service
        owner: root
        group: root
        mode: 0644
      become: true
      notify:
        - Restart pulpcore-api.service
        - Starting the health check

    - name: Set the pulpcore-api service state
      systemd:
        name: pulpcore-api.service
        state: started
        enabled: true
        daemon_reload: true
      become: true

  when: pulp_install_api_service |bool
