---
name: Pulp PR
on: push
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install prerequisites
        run: |
          pip install --upgrade pip
          sudo apt remove ansible
          pip install --pre ansible-core
          pip install molecule docker molecule-docker ansible-lint[yamllint]
          ansible-galaxy collection install --force community.general -p ./temp
          ansible-galaxy collection install --force community.crypto -p ./temp
          mkdir -p plugins/modules
          cp temp/ansible_collections/community/general/plugins/modules/files/ini_file.py plugins/modules
          cp temp/ansible_collections/community/general/plugins/modules/system/seport.py plugins/modules
          cp temp/ansible_collections/community/crypto/plugins/modules/openssl_privatekey.py plugins/modules
          cp temp/ansible_collections/community/crypto/plugins/modules/openssl_publickey.py plugins/modules

          cp temp/ansible_collections/community/general/plugins/modules/system/make.py plugins/modules
          cp temp/ansible_collections/community/general/plugins/modules/packaging/language/pip_package_info.py plugins/modules

          rm -rf temp
          make install
          mkdir -p ~/.ansible/collections/ansible_collections/pulp/pulp_installer
          ansible-galaxy collection install --force community.docker
          MOLECULE_PATH=$(pip show molecule | grep Location | cut -d' ' -f2)
          sed -i "/tasks:/i collections:" $MOLECULE_PATH/molecule_docker/playbooks/create.yml
          sed -i "/collections:/a - community.docker" $MOLECULE_PATH/molecule_docker/playbooks/create.yml
          sed -i "s/collections:/  collections:/g" $MOLECULE_PATH/molecule_docker/playbooks/create.yml
          sed -i "s/- community.docker/    - community.docker/g" $MOLECULE_PATH/molecule_docker/playbooks/create.yml
          cp -r ./build/collections/ansible_collections/pulp/pulp_installer/* ~/.ansible/collections/ansible_collections/pulp/pulp_installer
          sed -i "/roles:/i collections:" playbooks/example-source/playbook.yml
          sed -i "/collections:/a - pulp.pulp_installer" playbooks/example-source/playbook.yml
          sed -i "s/collections:/  collections:/g" playbooks/example-source/playbook.yml
          sed -i "s/- pulp.pulp_installer/    - pulp.pulp_installer/g" playbooks/example-source/playbook.yml
          ansible-galaxy collection install --requirements-file requirements.yml
      - name: Molecule
        run: |
          ansible --version
          molecule test --scenario-name source-static
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        shell: bash
