---
name: Pulp CI
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '15 0 * * *'
jobs:
  full_test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python: ["2.7", "3.6", "3.7", "3.8"]
        # TODO: Once we have more than 3x3, use separate variables
        # This Travis syntax will probably work on GHA:
        # https://docs.travis-ci.com/user/environment-variables/#defining-multiple-variables-per-item
        env:
          - TEST_TYPE: release-dynamic
          - TEST_TYPE: release-static
          - TEST_TYPE: release-upgrade
          - TEST_TYPE: source-dynamic
          - TEST_TYPE: source-static
          - TEST_TYPE: source-upgrade
          - TEST_TYPE: packages-static
          - TEST_TYPE: packages-dynamic
          - TEST_TYPE: packages-upgrade
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Set tox env for python 27
        if: matrix.python == '2.7'
        run: echo "::set-env name=TOXENV::py27-${{ matrix.env.TEST_TYPE }}"
      - name: Set tox env for python 36
        if: matrix.python == '3.6'
        run: echo "::set-env name=TOXENV::py36-${{ matrix.env.TEST_TYPE }}"
      - name: Set tox env for python 37
        if: matrix.python == '3.7'
        run: echo "::set-env name=TOXENV::py37-${{ matrix.env.TEST_TYPE }}"
      - name: Set tox env for python 38
        if: matrix.python == '3.8'
        run: echo "::set-env name=TOXENV::py38-${{ matrix.env.TEST_TYPE }}"
      - name: Pulling images for PyPI upgrades
        if: matrix.env.TEST_TYPE == 'release-upgrade' || matrix.env.TEST_TYPE == 'source-upgrade'
        run: |
          docker pull quay.io/pulp/pulp-ci-dbuster:3.0.0
          docker pull quay.io/pulp/pulp-ci-c7:3.0.0
          docker pull quay.io/pulp/pulp-ci-f31:3.0.0
      - name: Pulling images for distro packages upgrades
        if: matrix.env.TEST_TYPE == 'packages-upgrade'
        run: |
          docker pull quay.io/pulp/pulp-ci-pkgs-c7:3.3.1
          docker pull quay.io/pulp/pulp-ci-pkgs-c8:3.3.1
      - name: Run tox
        run: tox
        env:
          TEST_TYPE: ${{ matrix.env.TEST_TYPE }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        shell: bash
